import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

const PRIMARY = "#0B5ED7";
const SECONDARY = "#6C757D";
const LIGHT = "#F8F9FA";
const BORDER = "#D9D9D9";
const SUCCESS = "#198754";  // Paid
const WARNING = "#FFC107";  // Partial
const DANGER = "#DC3545";   // Pending
const INFO = "#0DCAF0";     // Overdue

const PAGE_MARGIN = 40;
const PAGE_WIDTH = 515; // usable width (595 - 2*40)

const formatCurrency = (amount = 0) => {
  const n = Number(amount) || 0;
  return `${n.toLocaleString("en-IN")}`;
  // NOTE: pdfkit's built-in "Helvetica" font has NO glyph for "₹" (it will
  // render as a black box). This is why the document registers and uses the
  // bundled DejaVu Sans font ("FS-Regular" / "FS-Bold") below instead of
  // "Helvetica" everywhere — DejaVu Sans includes the ₹ (U+20B9) glyph.
};

const formatDate = (date) => {
  if (!date) return "-";
  const d = new Date(date);
  if (isNaN(d.getTime())) return "-";
  return d.toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
};

const maskAccount = (number = "") => {
  const str = String(number || "");
  if (!str) return "-";
  return str.replace(/\d(?=\d{4})/g, "X");
};

// pdfkit needs strings; guard against numbers/undefined/null everywhere.
const safe = (val) => {
  if (val === undefined || val === null || val === "") return "-";
  return String(val);
};

function drawSection(doc, title, y) {
  doc.roundedRect(PAGE_MARGIN, y, PAGE_WIDTH, 25, 6).fill(PRIMARY);

  doc
    .fillColor("white")
    .font("FS-Bold")
    .fontSize(12)
    .text(title, PAGE_MARGIN + 10, y + 7);

  doc.fillColor("black");

  return y + 35;
}

function drawLabelValue(doc, label, value, x, y, width = 220) {
  doc
    .font("FS-Bold")
    .fontSize(9)
    .fillColor(SECONDARY)
    .text(label, x, y);

  doc
    .font("FS-Regular")
    .fontSize(10)
    .fillColor("black")
    .text(safe(value), x, y + 13, { width });
}

function drawHorizontalLine(doc, y) {
  doc
    .strokeColor(BORDER)
    .lineWidth(1)
    .moveTo(PAGE_MARGIN, y)
    .lineTo(PAGE_MARGIN + PAGE_WIDTH, y)
    .stroke();
}

function addHeader(doc, loan) {
  const logoPath = path.join(process.cwd(), "assets/logo.png");

  if (fs.existsSync(logoPath)) {
    doc.image(logoPath, PAGE_MARGIN, 20, { width: 55 });
  }

  doc
    .fillColor(PRIMARY)
    .font("FS-Bold")
    .fontSize(24)
    .text("FinSarthi", 105, 28);

  doc.fillColor(SECONDARY).fontSize(11).text("Loan EMI Statement", 105, 56);

  doc.fontSize(9).fillColor("black");

  doc.text(`Statement Date : ${formatDate(new Date())}`, 350, 30, {
    width: 205,
    align: "right",
  });

  doc.text(`Report ID : ${safe(loan.loanNumber)}-${Date.now()}`, 350, 45, {
    width: 205,
    align: "right",
  });

  drawHorizontalLine(doc, 90);
}

function addFooter(doc, pageIndex, pageCount) {
  // IMPORTANT: with a 40pt page margin on A4 (842pt tall), the usable area
  // ends at y=802. Anything drawn past that trips pdfkit's automatic
  // pagination (it silently inserts a *new* page for the overflowing text),
  // which is what caused extra blank pages before. Keep every footer line
  // comfortably under 802, and pass lineBreak:false as a second safety net.
  const bottom = 755;
  const opts = { lineBreak: false };

  drawHorizontalLine(doc, bottom - 10);

  doc
    .fontSize(8)
    .fillColor(SECONDARY)
    .font("FS-Regular")
    .text("Generated by FinSarthi Loan Management System", PAGE_MARGIN, bottom, opts);

  doc.text("Confidential Loan Statement", PAGE_MARGIN, bottom + 12, opts);

  doc.text(`Generated : ${new Date().toLocaleString("en-IN")}`, PAGE_MARGIN, bottom + 24, opts);

  doc.text(`Page ${pageIndex} of ${pageCount}`, PAGE_MARGIN, bottom + 24, {
    width: PAGE_WIDTH,
    align: "right",
    lineBreak: false,
  });
}

function getStatusColor(status) {
  switch (String(status || "").toUpperCase()) {
    case "PAID":
      return SUCCESS;
    case "PARTIAL":
      return WARNING;
    case "OVERDUE":
      return INFO;
    case "PENDING":
    case "DUE":
      return DANGER;
    default:
      return SECONDARY;
  }
}

// Checks remaining vertical space; adds a new page (with header + optional
// re-drawn table header) if not enough room is left before the footer zone.
function ensureSpace(doc, loan, y, needed, opts = {}) {
  const FOOTER_ZONE = 760;
  if (y + needed <= FOOTER_ZONE) return y;

  doc.addPage();
  addHeader(doc, loan);
  let newY = 110;

  if (opts.sectionTitle) {
    newY = drawSection(doc, opts.sectionTitle, newY);
  }
  if (opts.afterBreak) {
    newY = opts.afterBreak(newY);
  }
  return newY;
}

export const generateLoanStatementPDF = async (data, res) => {
  const loan = data || {};
  const repaymentSchedule = Array.isArray(loan.repaymentSchedule)
    ? loan.repaymentSchedule
    : [];

  const doc = new PDFDocument({
    size: "A4",
    margin: PAGE_MARGIN,
    bufferPages: true,
  });

  // Register a Unicode-capable font so the ₹ symbol renders correctly.
  // (The default "Helvetica" built into pdfkit does not have a ₹ glyph.)
  const fontDir = path.join(process.cwd(), "assets/fonts");
  const regularFontPath = path.join(fontDir, "DejaVuSans.ttf");
  const boldFontPath = path.join(fontDir, "DejaVuSans-Bold.ttf");

  if (fs.existsSync(regularFontPath) && fs.existsSync(boldFontPath)) {
    doc.registerFont("FS-Regular", regularFontPath);
    doc.registerFont("FS-Bold", boldFontPath);
  } else {
    // Fallback so the code never crashes even if the font files are missing
    // — but the ₹ symbol will render as a box in that case.
    doc.registerFont("FS-Regular", "Helvetica");
    doc.registerFont("FS-Bold", "Helvetica-Bold");
  }

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `inline; filename=${safe(loan.loanNumber).replace(/[^a-zA-Z0-9_-]/g, "_")}.pdf`
  );

  doc.pipe(res);

  addHeader(doc, loan);

  let y = 110;

  // =============================================
  // BORROWER INFORMATION
  // =============================================
  y = drawSection(doc, "Borrower Information", y);

  drawLabelValue(doc, "Customer Name", loan.borrower?.name, 45, y);
  drawLabelValue(doc, "Customer ID", loan.borrower?.customerId, 300, y);
  y += 42;

  drawLabelValue(doc, "Loan ID", loan.loanNumber, 45, y);
  drawLabelValue(doc, "Loan Type", loan.productName, 300, y);
  y += 42;

  drawLabelValue(doc, "Mobile Number", loan.borrower?.mobile, 45, y);
  drawLabelValue(doc, "Email", loan.borrower?.email, 300, y);
  y += 42;

  drawLabelValue(doc, "Address", loan.borrower?.address, 45, y, 470);
  y += 55;

  // =============================================
  // LOAN DETAILS
  // =============================================
  y = drawSection(doc, "Loan Details", y);

  drawLabelValue(doc, "Loan Amount", formatCurrency(loan.loanAmount), 45, y);
  drawLabelValue(
    doc,
    "Interest Rate",
    loan.interestRate !== undefined ? `${loan.interestRate}%` : "-",
    300,
    y
  );
  y += 42;

  drawLabelValue(
    doc,
    "Loan Tenure",
    loan.tenure !== undefined ? `${loan.tenure} Months` : "-",
    45,
    y
  );
  drawLabelValue(doc, "EMI Amount", formatCurrency(loan.emiAmount), 300, y);
  y += 42;

  drawLabelValue(doc, "Total Interest", formatCurrency(loan.totalInterest), 45, y);
  drawLabelValue(doc, "Total Payable", formatCurrency(loan.totalPayable), 300, y);
  y += 42;

  drawLabelValue(doc, "Loan Start Date", formatDate(loan.loanStartDate), 45, y);
  drawLabelValue(doc, "Loan End Date", formatDate(loan.loanEndDate), 300, y);
  y += 42;

  drawLabelValue(doc, "Next EMI Date", formatDate(loan.nextEMIDate), 45, y);

  // Loan status shown as a small colored pill instead of plain text
  const statusLabel = safe(loan.status);
  doc.font("FS-Bold").fontSize(9).fillColor(SECONDARY).text("Loan Status", 300, y);
  const pillColor = statusLabel.toUpperCase() === "CLOSED" ? SECONDARY : SUCCESS;
  doc.roundedRect(300, y + 12, 80, 16, 8).fill(pillColor);
  doc
    .fillColor("white")
    .font("FS-Bold")
    .fontSize(8)
    .text(statusLabel, 300, y + 16, { width: 80, align: "center" });
  doc.fillColor("black");
  y += 60;

  // =============================================
  // BANK DETAILS
  // =============================================
  y = ensureSpace(doc, loan, y, 140);
  y = drawSection(doc, "Bank Details", y);

  drawLabelValue(doc, "Bank Name", loan.bank?.bankName, 45, y);
  drawLabelValue(doc, "Account Holder", loan.bank?.accountHolderName, 300, y);
  y += 42;

  drawLabelValue(doc, "Account Number", maskAccount(loan.bank?.accountNumber), 45, y);
  drawLabelValue(doc, "IFSC", loan.bank?.ifscCode, 300, y);
  y += 42;

  drawLabelValue(doc, "Branch", loan.bank?.branchName, 45, y);
  drawLabelValue(doc, "Account Type", loan.bank?.accountType, 300, y);
  y += 60;

  // =============================================
  // DISBURSEMENT DETAILS
  // =============================================
  y = ensureSpace(doc, loan, y, 130);
  y = drawSection(doc, "Disbursement Details", y);

  drawLabelValue(doc, "Disbursed Amount", formatCurrency(loan.disbursement?.amount), 45, y);
  drawLabelValue(doc, "Transfer Method", loan.disbursement?.method, 300, y);
  y += 42;

  drawLabelValue(doc, "UTR Number", loan.disbursement?.utrNumber, 45, y);
  drawLabelValue(doc, "Transfer Status", loan.disbursement?.status, 300, y);
  y += 42;

  drawLabelValue(doc, "Processed At", formatDate(loan.disbursement?.processedAt), 45, y);
  y += 70;

  // =============================================
  // EMI PAYMENT HISTORY
  // =============================================
  y = ensureSpace(doc, loan, y, 100);
  y = drawSection(doc, "EMI Payment History", y);

  const rowHeight = 24;

  // Widths sum to PAGE_WIDTH (515) so the table fills the full section width.
  const columns = [
    { key: "no", label: "EMI", width: 35, align: "center" },
    { key: "due", label: "Due Date", width: 65, align: "center" },
    { key: "emi", label: "EMI Amt", width: 65, align: "right" },
    { key: "paid", label: "Paid", width: 65, align: "right" },
    { key: "payDate", label: "Pay Date", width: 65, align: "center" },
    { key: "utr", label: "UTR", width: 100, align: "center" },
    { key: "mode", label: "Mode", width: 55, align: "center" },
    { key: "status", label: "Status", width: 65, align: "center" },
  ];

  function drawTableHeader(yPos) {
    doc.rect(PAGE_MARGIN, yPos, PAGE_WIDTH, rowHeight).fill(PRIMARY);

    let x = PAGE_MARGIN;
    doc.fillColor("white").font("FS-Bold").fontSize(8);
    columns.forEach((col) => {
      doc.text(col.label, x + 4, yPos + 8, { width: col.width - 8, align: col.align });
      x += col.width;
    });
    doc.fillColor("black");
  }

  drawTableHeader(y);
  y += rowHeight;

  if (repaymentSchedule.length === 0) {
    doc
      .font("FS-Regular")
      .fontSize(9)
      .fillColor(SECONDARY)
      .text("No EMI schedule available.", PAGE_MARGIN + 4, y + 6);
    y += rowHeight;
  }

  repaymentSchedule.forEach((emi, index) => {
    if (y + rowHeight > 730) {
      doc.addPage();
      addHeader(doc, loan);
      y = 110;
      y = drawSection(doc, "EMI Payment History", y);
      drawTableHeader(y);
      y += rowHeight;
    }

    if (index % 2 === 0) {
      doc.rect(PAGE_MARGIN, y, PAGE_WIDTH, rowHeight).fill(LIGHT);
    }

    doc.strokeColor(BORDER).lineWidth(1).rect(PAGE_MARGIN, y, PAGE_WIDTH, rowHeight).stroke();

    let x = PAGE_MARGIN;
    const rowValues = {
      no: safe(emi.installmentNumber),
      due: formatDate(emi.dueDate),
      emi: formatCurrency(emi.emiAmount),
      paid: formatCurrency(emi.paidAmount || 0),
      payDate: emi.paymentDate ? formatDate(emi.paymentDate) : "-",
      utr: safe(emi.utrNumber),
      mode: safe(emi.paymentMode),
      status: safe(emi.status),
    };

    columns.forEach((col) => {
      if (col.key === "status") {
        doc
          .fillColor(getStatusColor(emi.status))
          .font("FS-Bold")
          .fontSize(8)
          .text(rowValues[col.key], x + 4, y + 8, { width: col.width - 8, align: col.align });
      } else {
        doc
          .fillColor("black")
          .font("FS-Regular")
          .fontSize(8)
          .text(rowValues[col.key], x + 4, y + 8, { width: col.width - 8, align: col.align });
      }
      x += col.width;
    });

    y += rowHeight;
  });

  y += 30;

  // =============================================
  // LOAN SUMMARY
  // =============================================
  y = ensureSpace(doc, loan, y, 220, { sectionTitle: "Loan Summary" });
  if (y === 110 + 35) {
    // ensureSpace already drew the section on the new page
  } else {
    y = drawSection(doc, "Loan Summary", y);
  }

  const summary = loan.summary || {};

  const summaryData = [
    ["Total EMI Count", safe(summary.totalInstallments ?? repaymentSchedule.length)],
    ["Paid EMI", safe(summary.paidInstallments ?? 0)],
    ["Pending EMI", safe(summary.pendingInstallments ?? 0)],
    ["Overdue EMI", safe(summary.overdueInstallments ?? 0)],
    ["Total Amount Paid", formatCurrency(summary.totalAmountPaid || 0)],
    ["Remaining Amount", formatCurrency(summary.remainingAmount || 0)],
    ["Outstanding Principal", formatCurrency(summary.outstandingPrincipal || 0)],
    ["Outstanding Interest", formatCurrency(summary.outstandingInterest || 0)],
    ["Collection %", `${summary.collectionPercentage ?? 0}%`],
  ];

  const leftX = 45;
  const rightX = 300;
  const boxWidth = 220;
  const boxHeight = 30;
  const rowGap = 40;
  let boxY = y;

  summaryData.forEach((item, index) => {
    const x = index % 2 === 0 ? leftX : rightX;

    if (index !== 0 && index % 2 === 0) {
      boxY += rowGap;
    }

    doc.roundedRect(x, boxY, boxWidth, boxHeight, 5).fill(LIGHT).stroke(BORDER);

    doc
      .fillColor(SECONDARY)
      .font("FS-Bold")
      .fontSize(8)
      .text(item[0], x + 10, boxY + 6);

    doc
      .fillColor(PRIMARY)
      .font("FS-Bold")
      .fontSize(10)
      .text(item[1], x + 10, boxY + 17);
  });

  y = boxY + boxHeight + 20;

  // =============================================
  // ELECTRONIC STAMP
  // =============================================
  y = ensureSpace(doc, loan, y, 55);

  doc.roundedRect(40, y, PAGE_WIDTH, 45, 5).fill("#EAF4FF");

  doc
    .fillColor(PRIMARY)
    .font("FS-Bold")
    .fontSize(11)
    .text("Electronically Generated Statement", 55, y + 10);

  doc
    .fillColor(SECONDARY)
    .font("FS-Regular")
    .fontSize(9)
    .text(
      "This is a computer-generated loan statement. No physical signature is required.",
      55,
      y + 24
    );

  doc.fillColor("black");

  // =============================================
  // WATERMARK + FOOTER (applied to every buffered page)
  // =============================================
  const pages = doc.bufferedPageRange();

  for (let i = pages.start; i < pages.start + pages.count; i++) {
    doc.switchToPage(i);

    doc.save();
    doc.rotate(-35, { origin: [300, 450] });
    doc
      .fillColor("#EEEEEE")
      .opacity(0.18)
      .fontSize(65)
      .font("FS-Bold")
      .text("FINSARTHI", 120, 380);
    doc.restore();
    doc.opacity(1);

    addFooter(doc, i - pages.start + 1, pages.count);
  }

  doc.end();

  // Let caller await completion when res is a stream that emits 'finish'
  // (e.g. a real HTTP response or fs.createWriteStream) so PDF generation
  // can be awaited in calling code instead of firing-and-forgetting.
  return new Promise((resolve, reject) => {
    if (typeof res.on === "function") {
      res.on("finish", resolve);
      res.on("error", reject);
    } else {
      resolve();
    }
  });
};